### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ritch** [mcollina/ascoltatori#110]
@mcollina 

I've looked through the examples and some the implementation and could not find any details on handling errors. From what I can tell there isn't a standard. It looks like I am suppose to use domains to handle all errors.

I'd like to avoid the overhead of domains and implement error handling in a way that works for all stores. I'd also like to be able to associate the error with the action performed (eg. connect, publish, subscribe). Is this possible?

Here is some code that illustrates the differences I am seeing.

```js
// mongo
store.publish(topic, msg, function(err) {
  if(err) handlerError(err); // might error on insert
});

// mqtt
try {
  store.publish(topic, msg, function(err) {
    // i'll never get an error here...
  });
} catch(e) {
  handleError(e); // maybe connection is closed
}
```

Here's essentially what I'd like to be able to do (although I am open to suggestions or current best practices).

```js
// for all types of store
store.publish(topic, msg, function(err) {
  if(err) handlerError(err); // connection err (usually connection closing / closed), store specific err (eg. mongo insert)
});
```

AFAICT (without looking too closely at the code). In order to support the example above we would need to rework things like [_raiseIfClosed()](https://github.com/mcollina/ascoltatori/blob/master/lib/mqtt_ascoltatore.js#L88).

**Comment by mcollina** [comment]
Thanks @ritch! I am in the process of refactoring this codebase into smaller modules: https://github.com/mcollina/mqemitter https://github.com/mcollina/mqemitter-redis https://github.com/mcollina/mqemitter-mongodb

Also to address some of these issues, as well as some design problems I have with this module.

Anyway, I am ok for accepting a PR here on this matter, if you want to work on it and help maintaining this module, too :).
