### ISSUE TITLE
Passing AMQP options as a string doesn't work

### ISSUE THREAD

**Issue by gfarrell** [mcollina/ascoltatori#111]
[amqp_ascolatatore.js#61](https://github.com/mcollina/ascoltatori/blob/a3589b5b3a04591cba2ff541e07f9f5dabaa9e7e/lib/amqp_ascoltatore.js#L61)

    conn = this._opts.amqp.createConnection(this._opts.client);

If you're not using localhost:5672, passing options as a string to [node-amqp](https://github.com/postwait/node-amqp), does not work. As per the documentation, this URL would have to be passed as a `url` key in the `options` object. E.g.

    conn = amqp.createConnection({ url: this._opts.client });

I have verified this manually.

Ascoltatori should really allow the passing of the options for `amqp.createConnection` fully, instead of just a `client` string, but in the meantime, it requires a fix.

**Comment by mcollina** [comment]
Sorry to ask, but why you are not passing a full object inside `client` vs a string? Maybe we should just update some doc somewhere.

**Comment by gfarrell** [comment]
Errrr yeah, I just realised that this is a silly solution to the problem; I think upsating the docs is a much better idea :D

**Comment by mcollina** [comment]
Which doc is wrong? Can you please submit a PR for that?

**Comment by gfarrell** [comment]
Actually I think this is my fault, I got it into my head that the client option was supposed to be a string, but looking at it again, I have no idea how I got that one into my head.
