### ISSUE TITLE
this._match([], 0, topic.split(this._separator), this._trie)

### ISSUE THREAD

**Issue by hongtoushizi** [mcollina/ascoltatori#115]
moscaServer-0 (err):     at EventEmitter.publish (/usr/lib/node_modules/mosca/lib/server.js:315:8)
moscaServer-0 (err):     at Client.handleAuthorizePublish (/usr/lib/node_modules/mosca/lib/client.js:481:15)
moscaServer-0 (err):     at /usr/lib/node_modules/mosca/lib/client.js:507:14
moscaServer-0 (err):     at EventEmitter.Server.authorizePublish (/usr/lib/node_modules/mosca/lib/server.js:378:3)
moscaServer-0 (err):     at Object._onImmediate (/usr/lib/node_modules/mosca/lib/client.js:506:19)
moscaServer-0 (err):     at processImmediate [as _immediateCallback] (timers.js:345:15)
moscaServer-0 (err): /usr/lib/node_modules/mosca/node_modules/qlobber/lib/qlobber.js:315
moscaServer-0 (err):     return this._match([], 0, topic.split(this._separator), this._trie);
moscaServer-0 (err):                                     ^
moscaServer-0 (err): TypeError: Cannot call method 'split' of undefined
moscaServer-0 (err):     at Matcher.Qlobber.match (/usr/lib/node_modules/mosca/node_modules/qlobber/lib/qlobber.js:315:37)
moscaServer-0 (err):     at RedisPersistence.storeOfflinePacket (/usr/lib/node_modules/mosca/lib/persistence/redis.js:340:34)
moscaServer-0 (err):     at EventEmitter.server.storePacket (/usr/lib/node_modules/mosca/lib/persistence/abstract.js:65:10)
moscaServer-0 (err):     at EventEmitter.publish (/usr/lib/node_modules/mosca/lib/server.js:315:8)
moscaServer-0 (err):     at Client.handleAuthorizePublish (/usr/lib/node_modules/mosca/lib/client.js:481:15)
moscaServer-0 (err):     at /usr/lib/node_modules/mosca/lib/client.js:507:14
moscaServer-0 (err):     at EventEmitter.Server.authorizePublish (/usr/lib/node_modules/mosca/lib/server.js:378:3)
moscaServer-0 (err):     at Object._onImmediate (/usr/lib/node_modules/mosca/lib/client.js:506:19)
moscaServer-0 (err):     at processImmediate [as _immediateCallback] (timers.js:345:15)

I don't know why ？  for your help...

**Comment by mcollina** [comment]
It's really hard to debug what's going on. You need to provide detailed
instructions on how to replicate.

>

**Comment by hongtoushizi** [comment]
Sorry, I can not provide too many things, because this error is not always happen. Occasionally occur several times in the production, it is difficult to reproduce. So I want to see if you can offer some advice
