### ISSUE TITLE
"npm test" fails

### ISSUE THREAD

**Issue by boneskull** [mcollina/ascoltatori#121]
Probably because I don't have a broker running, but there are no instructions on how to set up the test environment. 

From what I can gather from `.travis.yml`, I need:

- MongoDB
- Whatever this does: `(cd node_modules/mosca/node_modules && rm -rf ascoltatori && mkdir ascoltatori && tar -c --exclude node_modules ../../.. | tar -x -C ascoltatori)`
- RabbitMQ
- Redis
- `libzmq3-dev`

If you're going to force pre-commit hook(s), it should at least be trivial to run the tests.  So, either all this stuff is installed via a `prepublish` script--for Linux, Windows, and Darwin--or the pre-commit hook(s) should be removed.

**Comment by mcollina** [comment]
The pre-commit stays. Because you know what you are doing when you decide
to skip the tests. It's a failsafe.

Testing this module requires lots of stuff. And it is one of the reasons
why I want to split it into multiples ones.
Il giorno mar 30 giu 2015 alle 00:53 Christopher Hiller <
notifications@github.com> ha scritto:

**Comment by boneskull** [comment]
I don't really care about the hook, though it is frustrating to not know if my PRs work.  I just want to know what I need to run the tests.

**Comment by mcollina** [comment]
Install RabbitMQ, MongoDB, Redis and libzmq3-dev (zmq on Homebrew, if you are on Mac). You should be ok then.

**Comment by boneskull** [comment]
Any desire to add either an `install`, `prepublish` or ad hoc script that would install the deps (which would detect environment)?

**Comment by mcollina** [comment]
Maintaining those is really really hard and error prone (especially regarding windows).

I am ok to have these specified in the README or CONTRIBUTING, if you want to add them :).

**Comment by boneskull** [comment]
@mcollina A better idea might be to supply a `Vagrant` file and just have contributors `vagrant up` a machine which has everything preinstalled.

**Comment by mcollina** [comment]
That would be awesome! I am not a huge fan of vagrant, but I see the benefits here. Another solution might be a docker compose thing.

Anyway, I am up for any contribution in this area.
