### ISSUE TITLE
feature: public access to "_closed" property

### ISSUE THREAD

**Issue by boneskull** [mcollina/ascoltatori#123]
To immediately check whether or not an `*Ascolatore` is in the "closed" state, you can either read the (private) `_closed` property, or:

```js
var closed = false;
ascoltatore.on('closed', function() {
  closed = true;
})
  .on('ready', function() {
    closed = false;
  });
```

Best solution may be a read-only getter:

```js
Object.defineProperty(AbstractAscoltatore.prototype, 'closed', {
  get: function() {
    return this._closed;
  }
});
```

This avoids having to do something like rename `_closed` to `closed` everywhere, and discourages public writes to the flag.

**Comment by boneskull** [comment]
My *real* use case: I'd like to have the option of queuing publish or subscribe calls before the ascoltatore is connected, or while it is momentarily disconnected.  Having a property to check would be more convenient/performant than try/catch blocks.  Regardless, this is a *convenience*, and not anything crucial.

**Comment by boneskull** [comment]
(on the other hand, if I'm subscribing to the events it emits, then I should know)

**Comment by boneskull** [comment]
thank you, rubber duck.

**Comment by mcollina** [comment]
You are welcome!!
Il giorno sab 4 lug 2015 alle 08:35 Christopher Hiller <
notifications@github.com> ha scritto:
