### ISSUE TITLE
IP of clients

### ISSUE THREAD

**Issue by beinnova** [mcollina/ascoltatori#125]
Hi Matteo,
How I can obtain the IP of connected client? I guess I can use client argument passed to cb of clientConnected event?

Thx
Giorgio

**Comment by mcollina** [comment]
Are you referring to Mosca?

**Comment by beinnova** [comment]
​​
Yes! I'm sorry, wrong tab of my browser :smile:

2015-07-15 11:58 GMT+02:00 Matteo Collina <notifications@github.com>:

> Are you referring to Mosca?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcollina/ascoltatori/issues/125#issuecomment-121562103>
> .
>



-- 
*Be**innova* di *Giorgio Cerruti*
*WebSites | IT consultant | Web Developer*
*Phone: +39 340/87.68.326 :: Skype: beinnova*
*P.IVA: 10755560017*
*Visit Beinnova <http://www.beinnova.it> Site*

   - Giorgio Cerruti
   <http://it.linkedin.com/pub/giorgio-cerruti/31/422/852/>

**Comment by mcollina** [comment]
The `Client` object has a `conn` property. That is the incoming stream: which can be a TCP socket, a TLS socket or a https://www.npmjs.com/package/websocket-stream.
