### ISSUE TITLE
Project status 

### ISSUE THREAD

**Issue by goliatone** [mcollina/ascoltatori#139]
PRs seem to be piling up as well as issues. Honestly, there are not that many issues but at least one of them is pretty critical- #129- which seems to have an open PR #135 .

Is the library maintained?

**Comment by mcollina** [comment]
I have been having trouble in keep it updated.

@psorowka is doing some awesome work lately and a new version will be out soon.

**Comment by psorowka** [comment]
Thanks @mcollina but I won't take credits on this on my own. Without the work from @dario1985 and @davedoesdev and finally you we won't be so close to this as we are now 

Gesendet mit TypeApp
