### ISSUE TITLE
install ascoltatori fail

### ISSUE THREAD

**Issue by jonahzheng** [mcollina/ascoltatori#142]
make: Leaving directory `/root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/zmq        /build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/        build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gy        p.js" "rebuild"
gyp ERR! cwd /root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/zmq
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> buffertools@2.1.3 install /root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/        qlobber-fsq/node_modules/buffertools
> node-gyp rebuild

make: Entering directory `/root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/ql        obber-fsq/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/obj.target/buffertools.node
  COPY Release/buffertools.node
make: Leaving directory `/root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/qlo        bber-fsq/node_modules/buffertools/build'
npm WARN optional dep failed, continuing zmq@2.11.1

> fs-ext@0.4.6 install /root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobb        er-fsq/node_modules/fs-ext
> node-gyp configure build

make: Entering directory `/root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/ql        obber-fsq/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:27:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::i        mp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHa        ndleOrPersistent(v8::Handle<T>&)’ previously declared here
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::i        mp::NanEnsureLocal(v8::Handle<T>&)’
../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLoc        al(const v8::Local<T>&)’ previously declared here
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t,         int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, u        int32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, ui        nt32_t&)’ is ambiguous
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../fs-ext.cc:27:
/root/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::        Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
/root/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note:   no known conversion for argumen        t 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/root/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::        Buffer::New(v8::Isolate*, char*, size_t) <near match>
/root/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note:   no known conversion for argumen        t 2 from ‘const char*’ to ‘char*’
In file included from ../fs-ext.cc:27:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetC        urrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
make: Leaving directory `/root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/qlo        bber-fsq/node_modules/fs-ext/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/        build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gy        p.js" "configure" "build"
gyp ERR! cwd /root/msc/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/nod        e_modules/fs-ext
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing qlobber-fsq@0.3.1
ascoltatori@1.1.0 ascoltatori

**Comment by mcollina** [comment]
Fixed in v2.0.0
