### ISSUE TITLE
Kafka ascoltatore is not using HighLevelConsumer

### ISSUE THREAD

**Issue by svarkey** [mcollina/ascoltatori#158]
I have noticed the Kafka client as part of this integration is using the Simple consumer. As part of our project, we need to use HighLevelConsumer to get the queue functionality from Kafka.

To achieve the above we need to modify the _startConn method in  kafka_ascoltatore.js something like this 
````javascript 
if (useHighLevelConsumer) {
            that._consumer = new HighLevelConsumer(that._consumerClient, subscriptions, {
                groupId: groupId,
                fromOffset: true, autoCommit: false, encoding: "buffer"
            });
        } else {
            that._consumer = new Consumer(that._consumerClient, subscriptions, {
                groupId: groupId,
                fromOffset: true, autoCommit: false, encoding: "buffer"
            });
        }
````

**Comment by mcollina** [comment]
Would you like to send us a pull request? What's the difference between the two?

**Comment by svarkey** [comment]
The high level consumer can manage things like offset commits and rebalancing across consumer instances in a consumer group automatically.

Using the simple consumer you have to manage partition subscription, broker leader changes and offset commits yourself. The concept of a consumer group does not exist for the simple consumer API.

contents from here 
http://stackoverflow.com/questions/31482004/what-is-the-difference-between-simple-consumer-and-high-level-consumer

**Comment by svarkey** [comment]
Yes i can submit a pull request

**Comment by mcollina** [comment]
Thanks!

**Comment by svarkey** [comment]
I am getting 403 when i try to commit to this repo. Can you please add me as a committer? my username is svarkey

Thanks
Sanchu

**Comment by mcollina** [comment]
@svarkey you will need to press the fork button on the top right of github, commit there, and then send a pull request from that repo.

**Comment by svarkey** [comment]
Pull request created 
https://github.com/mcollina/ascoltatori/pull/159

**Comment by svarkey** [comment]
Issue verified on version 3.2.0. Closing this
