### ISSUE TITLE
Unsubscribe?

### ISSUE THREAD

**Issue by StrictlySkyler** [mcollina/ascoltatori#166]
Currently, doesn't look like there's a way to unsubscribe from a topic.  Are we expected to set `ascoltatore = null`?

**Comment by mcollina** [comment]
unsubsribe offers the same API of subscribe. Check the docs, the test or
the source code.
Il giorno gio 15 dic 2016 alle 00:43 Skyler Brungardt <
notifications@github.com> ha scritto:
