### ISSUE TITLE
Connection error with Kafka

### ISSUE THREAD

**Issue by Industrial** [mcollina/ascoltatori#169]
Hello.

I am trying to get Kafka working with Docker and Docker Compose in order to study Event Sourcing and CQRS.

Kafka takes a while to start and elect it's leader and the TCP port is already listening before it is 100% ready to accept connections it seems.

I am using the tool Dockerize to poll the TCP port and start my client Container after the port is being listened on. When I start my client service I still get Connection Refused errors. When I start Kafka first and the client container manually at a later time then it works.

I would like to build a retry strategy but I can not seem to pinpoint where the error is being thrown.

```
users_1      | events.js:161
users_1      |       throw er; // Unhandled 'error' event
users_1      |       ^
users_1      |
users_1      | Error: connect ECONNREFUSED 0.0.0.0:9092
users_1      |     at Object.exports._errnoException (util.js:1023:11)
users_1      |     at exports._exceptionWithHostPort (util.js:1046:20)
users_1      | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

The `ascoltatori.build()` callback is never fired (I have a log on the first line) before the error happens.

**Comment by Industrial** [comment]
It seems I'm getting an identical stack trace just using the `kafka-node` package.

**Comment by Industrial** [comment]
It seems the `kafka-node` package is not so dependable. I find it's source code quality lacking, there is no test coverage to speak of and it even breaks node core api's (calling callbacks with objects and arrays.. instead of errors)

I have found https://github.com/Blizzard/node-rdkafka which is very recently updated, seems well maintained and it's made by a multinational and uses a C library for stability and speed under the hood. This one might be the better option ;)

I'm going with this package for now (as I'm only using kafka, not other transports) so I'm closing this ticket.

**Comment by mcollina** [comment]
If anybody would like to update ascoltatori to node-rdkafka, I'll be happy to merge!
