### ISSUE TITLE
How to persistence message with Redis?

### ISSUE THREAD

**Issue by SeungUkLee** [mcollina/ascoltatori#170]
Hello. I am a Korean student who is interested in IoT. 

As I was studying IoT, I saw Mosca and Ascoltatori open source.

However, when I was studying Ascoltatori open source, I got a question.

How to persistence message with Redis?

this is my source :
`var ascoltatori = require('ascoltatori');

var settings = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: 6379,
  return_buffers: true,
  host: '127.0.0.1'
};

ascoltatori.build(settings, function (err, ascoltatore) {

  //subscribes to a topic
  ascoltatore.subscribe('hello', function() {
    console.log(arguments);
    // this print { '0': 'hello', '1': 'a message' '2':{}}
  });

  // publishes a message to the topic 'hello'
  ascoltatore.publish('hello', 'messgae', function() {
    console.log('message published');
  });
});`

When run with this source, the value is not stored in Redis.

**Comment by mcollina** [comment]
The value is passed _through_ redis pubsub, it is not stored. Mosca will persist the messages if they are retained or it's a QoS 1 subscription.
