### ISSUE TITLE
RabbitMQ MQTT Adapter

### ISSUE THREAD

**Issue by mohammed-barghash** [mcollina/ascoltatori#176]
Thank you for this interesting project. 
Does asccoltatori supports the bridging from AMQP to MQTT ?
If yes does it use the RabbitMQ MQTT adapter in that ?
If no then is it available from the ascoltatori interface to enabale this plugin (MQTT adapter) from RabbitMQ? please have a look at https://www.rabbitmq.com/mqtt.html.

Thank you in advance.

**Comment by mcollina** [comment]
No, it does not use the RabbitMQ MQTT adapter. Ascoltatori allows you to switch between multiple pub-sub systems without changing your codebase.
Mosca+Ascoltatori (with AMQP config) allows for a similar job that the MQTT does.
