### ISSUE TITLE
Wait for async handler?

### ISSUE THREAD

**Issue by theanimal666** [mcollina/ascoltatori#177]
Hi,

```javascript

const handler = async () => {
    await someAyncTask();
};
ascoltatore.subscribe(topic, handler);
```
currently the handler function is called and returns immediately, so that the next message is handled before the first one finished what causes race conditions in our  #application.
Ist there any possibility to wait for the async handler, so that if the subscriber becomes to slow, the messages stay in storage until the subscriber becomes ready?

thanks in advance for your help & kind regards,
christian

**Comment by mcollina** [comment]
Currently you can't as promises are not supported. You will need to write a little wrapper for your function to do this.

**Comment by theanimal666** [comment]
So a regular callback should work:

```javascript
const handler = async (done) => {
     await someAsyncTask();
     done();
};

ascoltatore.subscribe(topic, handler);
```

i'm quite sure i tried that but it did not work - the callee did not pass the done callback, got a ReferenceError

**Comment by mcollina** [comment]
you don't need `done`, as the first argument is the topic, and the second argument is the message.  The handler has no `done` function.

You should consider using https://www.npmjs.com/package/make-promises-safe as well.

**Comment by theanimal666** [comment]
Thanks for the fast answer but i think you misundestood my intention:

```javascript
let cnt = 0;
const handler = async () => {
     const i = cnt;
     cnt++;
     console.log('Start', i) 
     await asyncWait(100 * (3-i));
     console.log('End', i)
};
ascoltatore.subscribe(topic, handler);

ascoltatore.publish(topic);
ascoltatore.publish(topic);
ascoltatore.publish(topic);
```

this prints:

```
Start 0
Start 1
Start 2
End 2
End 1
End 0
```
but what i need is
```
Start 0
End 0
Start 1
End 1
Start 2
End 2
```

So in words, the handler function should be called strictly in serial - e.g wait for all async code to finish, then deliver and process the next message. It should never have two handler functions run in parallel.

**Comment by mcollina** [comment]
@theanimal666 that is not supported by this library.
Check out https://github.com/mcollina/mqemitter, which should implement the pattern you need (with callbacks).
