### ISSUE TITLE
How to increase number of document (topics for mosca)

### ISSUE THREAD

**Issue by syberkitten** [mcollina/ascoltatori#178]
Hi

I see there is a hard coded limit, why?
(mqtt brokers should handle thousands if not millions of topics)

is there no way to change it other then forking the project?

This causes a maximum cap inside the database of 10k topics.

```
  this.connectionParams = {
    capped: true,
    size: this._opts.size || 10 * 1024 * 1024, // 10 MB
    max: this._opts.max || 10000 // documents
  };
```

**Comment by syberkitten** [comment]
first opened a related issue in the Mosca.io project:
https://github.com/mcollina/mosca/issues/653

**Comment by mcollina** [comment]
This needs a maximum as the space is preallocated on disk. Just pick a large number. Those are for temporary/in-flight data.

**Comment by syberkitten** [comment]
can i pass this param to ascoltatori provider (I'm using mosca which)  or do i need to fork and change the code?

**Comment by mcollina** [comment]
yes you can.

**Comment by syberkitten** [comment]
Trying to remove the cap limit I get:
```
Error: Cannot recover. Collection is not capped.
    at /mongo_ascoltatore.js:241:26
```

What implications can there be fore not capping?
I need support for many topics, 10k is just for one client.

**Comment by mcollina** [comment]
@syberkitten the messages are not stored forever. This is the maximum number of messages that would be replayed in case of a failure or a dropped connection. 10-100k are good numbers, you don't need to store per user.

**Comment by syberkitten** [comment]
@mcollina Thanks for pointing that out, I was under the impression that only 10k topics are stored in the mongo store since there were never more then 10k topics in the db when observed.

so concerning architecture, is it true that:
A. all topics are stored in memory (up to the memory limit?)
B. if each user has 10k topics, they are all in memory unless persistent (clean:false), right?

**Comment by mcollina** [comment]
I don't think you understood. Please study how MongoDB capped collection work.

Messages are not stored unless they are retained or they are part of an offline subscription.

The TTL is needed to avoid the DB to run out of space and queue things indefinitely. But it applies to a different collection.

**Comment by syberkitten** [comment]
Thanks, I can see in the docs that TTL can be changed for retained messages,
is there an option to change the cap limit as well? (beyond 10k)

**Comment by mcollina** [comment]
yes. It must have a limit. Look at the source code.
