### ISSUE TITLE
Ascoltatori + Aedes

### ISSUE THREAD

**Issue by RuiWangGit** [mcollina/ascoltatori#186]
Hi, I am researching mqtt libraries for my next project.  wonder if ascoltatori can work with aedes? feels like Aedes already has everything good ascoltatori can provide. so what would be the best option/library to use if replay for missing packet is import. 

any input would be greatly appreciated. thanks.

**Comment by mcollina** [comment]
Aedes support mqemitter-compatibile libraries. mqemitter is designed to be a complete replacement of Ascoltatori. Something that is more maintenable (maintaining this is close to impossible now).
You should use those.
