### ISSUE TITLE
NPM reported vulnerability under ascoltatori

### ISSUE THREAD

**Issue by Karan1458** [mcollina/ascoltatori#191]
Versions : 
NPM : 6.4.1
Node : v8.11.4 LTS
ascoltatori: v4.3.0

$ npm audit
`Low             Prototype Pollution                                           
Package         lodash                                                        
Patched in      >=4.17.5                                                      
Dependency of   ascoltatori                                                   
Path            ascoltatori > kafka-node > lodash                             
More info       https://nodesecurity.io/advisories/577 
`
It's just open/ close issue. Confirming if maintainers are aware of this. 

Regards,
Karan

**Comment by mcollina** [comment]
Sure, don’t worry about it.
