### ISSUE TITLE
Implement deferred open

### ISSUE THREAD

**Issue by mcollina** [mcollina/ascoltatori#51]

**Comment by boneskull** [comment]
Along the same lines, it'd be really nice if ascoltatori could use the ubiquitous "`err, value`" callback style.

I say this because if I want to use, say, [bluebird](https://www.npmjs.com/package/bluebird) with it, the result is awkward:

```js
        return new Promise(function (resolve, reject) {
          try {
            ascoltatori.build(opts, resolve);
          } catch (err) {
            reject(err);
          }
        });
```

whereas if `err` was the first value to the callback:

```js
return Promise.promisify(ascoltatori.build)(opts);
```

**Comment by mcollina** [comment]
I agree 100%. Would you like to submit a PR for this?
Il giorno lun 29 giu 2015 alle 06:25 Christopher Hiller <
notifications@github.com> ha scritto:
