### ISSUE TITLE
Creating multiple packages

### ISSUE THREAD

**Issue by mcollina** [mcollina/ascoltatori#81]
I'm started thinking about splitting ascoltatori into multiple modules:
* ascoltatori
* ascoltatori-redis
* ascoltatori-amqp
* ascoltatori-mqtt
* ascoltatori-mongo
* ascoltatori-zmq

What do you think? @davedoesdev @andreareginato and whoever else is using this.

**Comment by boneskull** [comment]
I like the way it works now--the flexibility is attractive.

Say you have package `x` which depends on `ascoltatori`.  User of package `x` wants to use the `mqtt` broker, but could just as easily use the `zmq` one.  If `ascoltatori` was split, package `x` would need to add each of the resulting packages as dependencies.  Either way, package `x` needs all of it--but perhaps this is just my unique use case as the maintainer of package `x`.  :smile:

**Comment by mcollina** [comment]
Basically all that does is a big if, easily doable in yet another package.

Anyway, the new modules are http://npm.im/mqemitter,
http://npm.im/mqemitter-redis http://npm.im/mqemitter-mongodb.

They are much smaller in scope, as they were built only to support the new
version of Mosca.
Il giorno lun 29 giu 2015 alle 06:20 Christopher Hiller <
notifications@github.com> ha scritto:
